services:
  - type: web
    name: numlock
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn numlock.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:eRAZPRgbvQwLWMqFNBgBZkVrqlGQpLGa@postgres.railway.internal:5432/railway"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dcydv0ml9"
      - key: CLOUDINARY_API_KEY
        value: "972438774663272"
      - key: CLOUDINARY_API_SECRET
        value: "w5x5fcv1vlkN0xLBe7AuXhxjG6Y"