# Generated by Django 5.1.7 on 2025-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('device_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('device_issue', models.TextField()),
            ],
        ),
    ]
