# Generated by Django 5.1.7 on 2025-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_size_productimage_products_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subCategory',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('DELL', 'DELL'), ('MAC', 'MAC'), ('HP', 'HP')], max_length=100),
        ),
    ]
