# Generated by Django 5.1.7 on 2025-05-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_products_sizes_remove_products_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
